// src/app/components/Step4_Duration.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useWizard } from '../composables/useWizard'
import { getGoal } from './goalsData'
import NumericInputStepper from './ui/NumericInputStepper.vue'

const {
  setStep,
  durationYears,
  setDurationYears,
  goal,
  customGoalName,
  calculationFactors,
} = useWizard()

const currentGoal = computed(() => getGoal(goal.value))
const currentYear = computed(() => new Date().getFullYear())
const targetYear = computed(() => currentYear.value + durationYears.value)

const goalLabel = computed(() => {
  if (goal.value === 'custom') {
    return customGoalName.value || 'Ihr Ziel'
  }

  return currentGoal.value.label
})

const quickOptions = computed(() => currentGoal.value.typicalTimeHorizonOptions)

const handleBack = () => {
  if (calculationFactors.value.length > 0) {
    setStep(3)
    return
  }

  setStep(2)
}

const handleShowResult = () => {
  setStep(5)
}
</script>

<template>
  <div class="relative mx-auto flex min-h-[60vh] max-w-3xl flex-col items-center px-4 pb-12 pt-20">
    <button
      type="button"
      class="absolute left-4 top-8 flex items-center gap-2 text-sm font-medium text-[#568996] transition-colors hover:text-[#003745] md:left-0 md:top-8"
      @click="handleBack"
    >
      Zurueck
    </button>

    <div class="w-full">
      <div class="mb-12 text-center">
        <span class="mb-3 block text-sm font-medium uppercase tracking-widest text-[#EE0000]">Schritt 4 von 5</span>
        <h2 class="mb-4 text-3xl font-bold text-[#003745] md:text-4xl">Wann moechten Sie {{ goalLabel }} erreichen?</h2>
      </div>

      <div class="mb-12 grid grid-cols-3 gap-4">
        <button
          v-for="years in quickOptions"
          :key="years"
          type="button"
          class="py-4 text-lg font-medium transition-all"
          :class="
            durationYears === years
              ? 'border-2 border-[#003745] bg-[#003745]/10 text-[#003745]'
              : 'border border-[#003745]/20 bg-white text-[#568996] hover:border-[#003745]'
          "
          @click="setDurationYears(years)"
        >
          in {{ years }} Jahren
        </button>
      </div>

      <div class="mb-8 flex flex-col items-center rounded-[4px] border border-[#003745]/20 bg-white p-8">
        <div class="w-full max-w-sm">
          <NumericInputStepper
            :value="durationYears"
            :min="1"
            :max="40"
            :step="1"
            label="Laufzeit manuell anpassen"
            unit="Jahre"
            :note="`Zieljahr ${targetYear}`"
            @update:value="setDurationYears"
          />
        </div>
      </div>

      <div
        v-if="currentGoal.whatItMeans.length > 0"
        class="mb-8 flex items-start gap-4 rounded-[4px] border border-[#E6EEF0] bg-[#F4F9FA] p-5 text-sm leading-relaxed text-[#003745]"
      >
        <div class="shrink-0 rounded-[4px] border border-[#E6EEF0] bg-white p-2 font-semibold">Info</div>
        <div class="pt-1">
          <p class="mb-1 font-semibold">Gut zu wissen:</p>
          <ul class="list-disc space-y-1 pl-4">
            <li v-for="point in currentGoal.whatItMeans" :key="point">{{ point }}</li>
          </ul>
        </div>
      </div>

      <div class="flex flex-col items-center justify-center">
        <span class="mb-4 block text-sm text-[#568996]">Fast geschafft. Gleich sehen Sie Ihren Plan.</span>
        <button
          type="button"
          class="w-full rounded-[4px] border border-[#003745] bg-[#003745] px-12 py-3 font-medium text-white transition-colors hover:bg-[#002C36] md:w-auto"
          @click="handleShowResult"
        >
          Ergebnis anzeigen
        </button>
      </div>
    </div>
  </div>
</template>

// src/app/components/Step4_Duration.tsx
import React from 'react';
import { useWizard } from './WizardContext';
import { motion } from 'motion/react';
import { Minus, Plus, ArrowRight, Clock, Info, ChevronLeft } from 'lucide-react';
import clsx from 'clsx';
import { Button } from './ui/button';
import { getGoal } from './goalsData';

export const Step4_Duration = () => {
  const { setStep, durationYears, setDurationYears, goal, customGoalName, calculationFactors } = useWizard();
  const currentYear = new Date().getFullYear();
  const targetYear = currentYear + durationYears;

  const currentGoal = getGoal(goal);
  const goalLabel = goal === 'custom' ? customGoalName : currentGoal.label;
  const quickOptions = currentGoal.typicalTimeHorizonOptions;

  const handleBack = () => {
    // If user has selected calculation factors, they likely came from Step 3
    if (calculationFactors.length > 0) {
      setStep(3);
    } else {
      setStep(2);
    }
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-[60vh] max-w-3xl mx-auto px-4 pt-20 pb-12 relative">
      <button 
        onClick={handleBack}
        className="absolute left-4 top-8 md:left-0 md:top-8 text-[#568996] hover:text-[#003745] flex items-center gap-2 text-sm font-medium transition-colors"
      >
        <ChevronLeft size={16} /> Zurück
      </button>

      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="w-full"
      >
        <div className="text-center mb-12">
          <span className="text-[#EE0000] font-medium text-sm tracking-widest uppercase mb-3 block">
            Schritt 4 von 5
          </span>
          <h2 className="text-3xl md:text-4xl font-bold text-[#003745] mb-4">
            Wann möchten Sie {goalLabel} erreichen?
          </h2>
        </div>

        {/* Quick Options */}
        <div className="grid grid-cols-3 gap-4 mb-12">
          {quickOptions.map(years => (
            <button
              key={years}
              onClick={() => setDurationYears(years)}
              className={clsx(
                "py-4 rounded-none text-lg font-medium transition-all",
                durationYears === years
                  ? "border-2 border-[#003745] bg-[#003745]/10 text-[#003745]"
                  : "border border-[#003745]/20 bg-white text-[#568996] hover:border-[#003745]"
              )}
            >
              in {years} Jahren
            </button>
          ))}
        </div>

        {/* Manual Stepper */}
        <div className="bg-white rounded-[4px] p-8 border border-[#003745]/20 shadow-none mb-8 flex flex-col items-center">
          <div className="flex items-center justify-between w-full max-w-sm mb-4">
            <button 
              onClick={() => setDurationYears(Math.max(1, durationYears - 1))}
              disabled={durationYears <= 1}
              aria-label="Wert verringern"
              className={clsx(
                "w-12 h-12 rounded-none flex items-center justify-center transition-colors shadow-none border-none outline-none focus-visible:ring-2 focus-visible:ring-[#0043B4] focus-visible:outline-none",
                durationYears <= 1 
                  ? "bg-[#D5DEE1] text-[#003745]/60 cursor-not-allowed" 
                  : "bg-[#003745] text-white hover:bg-[#002C36] active:bg-[#00222A]"
              )}
            >
              <Minus size={20} strokeWidth={1.5} />
            </button>
            
            <div className="text-center">
              <div className="text-4xl font-bold text-[#003745] mb-1">
                {durationYears} Jahre
              </div>
              <div className="text-[#568996] font-medium">
                Zieljahr {targetYear}
              </div>
            </div>

            <button 
              onClick={() => setDurationYears(Math.min(40, durationYears + 1))}
              disabled={durationYears >= 40}
              aria-label="Wert erhöhen"
              className={clsx(
                "w-12 h-12 rounded-none flex items-center justify-center transition-colors shadow-none border-none outline-none focus-visible:ring-2 focus-visible:ring-[#0043B4] focus-visible:outline-none",
                durationYears >= 40
                  ? "bg-[#D5DEE1] text-[#003745]/60 cursor-not-allowed"
                  : "bg-[#003745] text-white hover:bg-[#002C36] active:bg-[#00222A]"
              )}
            >
              <Plus size={20} strokeWidth={1.5} color={durationYears >= 40 ? "currentColor" : "white"} />
            </button>
          </div>
        </div>

        {/* Info Box */}
        {currentGoal.whatItMeans.length > 0 && (
          <div className="bg-[#F4F9FA] text-[#003745] p-5 rounded-[4px] text-sm leading-relaxed flex gap-4 mb-8 items-start border border-[#E6EEF0]">
            <div className="bg-white p-2 rounded-[4px] shrink-0 border border-[#E6EEF0]">
              <Clock size={20} className="text-[#003745]" strokeWidth={1.5} />
            </div>
            <div className="pt-1">
              <p className="font-semibold mb-1">Gut zu wissen:</p>
              <ul className="list-disc pl-4 space-y-1">
                {currentGoal.whatItMeans.map((text, i) => (
                  <li key={i}>{text}</li>
                ))}
              </ul>
            </div>
          </div>
        )}

        <div className="flex flex-col items-center justify-center">
          <span className="text-[#568996] text-sm mb-4 block">
            Fast geschafft – gleich sehen Sie Ihren Plan.
          </span>
          <Button
            onClick={() => setStep(5)}
            className="w-full md:w-auto flex items-center justify-center gap-2 px-12"
            size="lg"
          >
            Ergebnis anzeigen <ArrowRight size={18} />
          </Button>
        </div>
      </motion.div>
    </div>
  );
};
