// src/app/components/Step2_TargetAmountType.tsx
import React, { useState } from 'react';
import { useWizard } from './WizardContext';
import { motion } from 'motion/react';
import { Calculator, Coins, ArrowRight, CheckCircle2, Info, ChevronLeft } from 'lucide-react';
import { Button } from './ui/button';
import { WizardInput } from './ui/WizardInput';
import { getGoal } from './goalsData';

export const Step2_TargetAmountType = () => {
  const { setStep, setTargetAmount, targetAmount, goal, customGoalName } = useWizard();
  const [inputAmount, setInputAmount] = useState<string>(targetAmount > 0 ? targetAmount.toString() : '');
  
  const currentGoal = getGoal(goal);
  const goalLabel = goal === 'custom' ? customGoalName : currentGoal.label;

  const handleManualSubmit = () => {
    const val = parseInt(inputAmount.replace(/\D/g, ''), 10);
    if (!isNaN(val) && val > 0) {
      setTargetAmount(val);
      setStep(4); // Skip calculation step
    }
  };

  const handleCalculateClick = () => {
    setStep(3);
  };

  const handleBack = () => {
    setStep(1);
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-[60vh] max-w-5xl mx-auto px-4 pt-20 pb-12 relative">
      <button 
        onClick={handleBack}
        className="absolute left-4 top-8 md:left-0 md:top-8 text-[#568996] hover:text-[#003745] flex items-center gap-2 text-sm font-medium transition-colors"
      >
        <ChevronLeft size={16} /> Zurück
      </button>

      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="mb-12 text-center max-w-2xl"
      >
        <span className="text-[#EE0000] font-medium text-sm tracking-widest uppercase mb-3 block">
          Schritt 2 von 5
        </span>
        <h2 className="text-3xl md:text-4xl font-bold text-[#003745] mb-4">
          Wie viel möchten Sie für {goalLabel} ansparen?
        </h2>
        <p className="text-xl text-[#568996] font-light">
          {currentGoal.shortTeaser}
        </p>
      </motion.div>

      <div className="grid md:grid-cols-2 gap-8 w-full items-stretch">
        {/* Option 1: Manual Input */}
        <motion.div 
          whileHover={{ y: -5 }}
          className="bg-white rounded-[4px] p-8 border border-[#003745]/20 shadow-none hover:shadow-lg transition-all flex flex-col hover:border-[#003745]"
        >
          <div className="bg-[#F4F9FA] w-12 h-12 rounded-[4px] flex items-center justify-center mb-6 text-[#003745]">
            <Coins size={24} strokeWidth={1.5} />
          </div>
          <h3 className="text-xl font-bold text-[#003745] mb-3">Betrag eingeben</h3>
          <p className="text-[#568996] mb-8">
            Sie haben bereits eine konkrete Summe im Kopf?
          </p>
          
          <div className="mt-auto space-y-4">
            <div className="relative">
              <WizardInput
                type="text"
                value={inputAmount}
                onChange={(e) => setInputAmount(e.target.value)}
                placeholder="Betrag eingeben"
                className="text-lg p-4 h-14 pr-14 rounded-[4px]"
              />
              <span className="absolute right-4 top-1/2 -translate-y-1/2 text-[#9FB6BC] font-medium">EUR</span>
            </div>
            
            {currentGoal.avgTargetAmountHint && (
              <div className="bg-[#F4F9FA] text-[#003745] p-4 rounded-[4px] text-sm leading-relaxed flex gap-3 border border-[#E6EEF0]">
                <Info className="shrink-0 mt-0.5 text-[#003745]" size={16} />
                {currentGoal.avgTargetAmountHint}
              </div>
            )}

            <div>
              <span className="text-[#568996] text-sm mb-4 block text-center">
                Als Nächstes legen Sie die Laufzeit fest.
              </span>
              <Button
                onClick={handleManualSubmit}
                disabled={!inputAmount}
                variant="secondary"
                className="w-full flex items-center justify-center gap-2"
                size="lg"
              >
                Mit diesem Betrag fortfahren <ArrowRight size={18} />
              </Button>
            </div>
          </div>
        </motion.div>

        {/* Option 2: Calculate */}
        <motion.div 
          whileHover={{ y: -5 }}
          className="bg-white rounded-[4px] p-8 border border-[#003745]/20 shadow-none hover:shadow-lg transition-all flex flex-col relative overflow-hidden hover:border-[#003745]"
        >
          <div className="bg-[#F4F9FA] w-12 h-12 rounded-[4px] flex items-center justify-center mb-6 text-[#003745]">
            <Calculator size={24} strokeWidth={1.5} />
          </div>
          <h3 className="text-xl font-bold text-[#003745] mb-3">Betrag ermitteln</h3>
          <p className="text-[#568996] mb-6">
            Wir helfen Ihnen, den passenden Betrag zu finden – basierend auf:
          </p>

          <div className="flex flex-wrap gap-2 mb-8 content-start">
            {currentGoal.amountFinderCategories.map((cat, i) => (
              <span key={i} className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-[#F4F9FA] text-[#003745] rounded-full text-xs font-medium border border-[#E6EEF0]">
                <CheckCircle2 size={12} /> {cat}
              </span>
            ))}
          </div>

          <div className="mt-auto">
            <span className="text-[#568996] text-sm mb-4 block text-center">
              Als Nächstes legen wir Prioritäten fest.
            </span>
            <Button
              onClick={handleCalculateClick}
              variant="outline"
              className="w-full flex items-center justify-center gap-2"
              size="lg"
            >
              Betrag ermitteln <ArrowRight size={18} />
            </Button>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

// src/app/components/Step2_TargetAmountType.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useWizard } from '../composables/useWizard'
import { parseEuroInput } from '../domain/wizardValidation'
import { getGoal } from './goalsData'

const {
  setStep,
  setTargetAmount,
  targetAmount,
  goal,
  customGoalName,
} = useWizard()

const inputAmount = ref(targetAmount.value > 0 ? String(targetAmount.value) : '')

const currentGoal = computed(() => getGoal(goal.value))

const goalLabel = computed(() => {
  if (goal.value === 'custom') {
    return customGoalName.value || 'Ihr Ziel'
  }

  return currentGoal.value.label
})

const parsedAmount = computed(() => parseEuroInput(inputAmount.value))

const handleManualSubmit = () => {
  if (parsedAmount.value === null) {
    return
  }

  setTargetAmount(parsedAmount.value)
  setStep(4)
}

const handleCalculateClick = () => {
  setStep(3)
}

const handleBack = () => {
  setStep(1)
}
</script>

<template>
  <div class="relative mx-auto flex min-h-[60vh] max-w-5xl flex-col items-center px-4 pb-12 pt-20">
    <button
      type="button"
      class="absolute left-4 top-8 flex items-center gap-2 text-sm font-medium text-[#568996] transition-colors hover:text-[#003745] md:left-0 md:top-8"
      @click="handleBack"
    >
      Zurueck
    </button>

    <div class="mb-12 max-w-2xl text-center">
      <span class="mb-3 block text-sm font-medium uppercase tracking-widest text-[#EE0000]">Schritt 2 von 5</span>
      <h2 class="mb-4 text-3xl font-bold text-[#003745] md:text-4xl">Wie viel moechten Sie fuer {{ goalLabel }} ansparen?</h2>
      <p class="text-xl font-light text-[#568996]">{{ currentGoal.shortTeaser }}</p>
    </div>

    <div class="grid w-full items-stretch gap-8 md:grid-cols-2">
      <article class="flex flex-col rounded-[4px] border border-[#003745]/20 bg-white p-8 transition-all hover:border-[#003745] hover:shadow-lg">
        <div class="mb-6 inline-flex h-12 w-12 items-center justify-center rounded-[4px] bg-[#F4F9FA] text-[#003745]">
          EUR
        </div>
        <h3 class="mb-3 text-xl font-bold text-[#003745]">Betrag eingeben</h3>
        <p class="mb-8 text-[#568996]">Sie haben bereits eine konkrete Summe im Kopf?</p>

        <div class="mt-auto space-y-4">
          <div class="relative">
            <input
              v-model="inputAmount"
              type="text"
              inputmode="numeric"
              autocomplete="off"
              placeholder="Betrag eingeben"
              class="h-14 w-full rounded-[4px] border border-[#003745]/20 p-4 pr-14 text-lg text-[#003745] outline-none focus:border-[#003745] focus:ring-1 focus:ring-[#003745]"
            />
            <span class="absolute right-4 top-1/2 -translate-y-1/2 font-medium text-[#9FB6BC]">EUR</span>
          </div>

          <div
            v-if="currentGoal.avgTargetAmountHint"
            class="flex gap-3 rounded-[4px] border border-[#E6EEF0] bg-[#F4F9FA] p-4 text-sm leading-relaxed text-[#003745]"
          >
            <span class="mt-0.5 shrink-0 font-semibold">Info</span>
            <span>{{ currentGoal.avgTargetAmountHint }}</span>
          </div>

          <div>
            <span class="mb-4 block text-center text-sm text-[#568996]">Als Naechstes legen Sie die Laufzeit fest.</span>
            <button
              type="button"
              :disabled="parsedAmount === null"
              class="w-full rounded-[4px] border border-[#003745] bg-[#003745] px-4 py-3 font-medium text-white transition-colors hover:bg-[#002C36] disabled:cursor-not-allowed disabled:border-[#D5DEE1] disabled:bg-[#D5DEE1] disabled:text-[#003745]/60"
              @click="handleManualSubmit"
            >
              Mit diesem Betrag fortfahren
            </button>
          </div>
        </div>
      </article>

      <article class="relative flex flex-col overflow-hidden rounded-[4px] border border-[#003745]/20 bg-white p-8 transition-all hover:border-[#003745] hover:shadow-lg">
        <div class="mb-6 inline-flex h-12 w-12 items-center justify-center rounded-[4px] bg-[#F4F9FA] text-[#003745]">
          Fx
        </div>
        <h3 class="mb-3 text-xl font-bold text-[#003745]">Betrag ermitteln</h3>
        <p class="mb-6 text-[#568996]">Wir helfen Ihnen, den passenden Betrag zu finden, basierend auf:</p>

        <div class="mb-8 flex flex-wrap content-start gap-2">
          <span
            v-for="category in currentGoal.amountFinderCategories"
            :key="category"
            class="inline-flex items-center rounded-full border border-[#E6EEF0] bg-[#F4F9FA] px-3 py-1.5 text-xs font-medium text-[#003745]"
          >
            {{ category }}
          </span>
        </div>

        <div class="mt-auto">
          <span class="mb-4 block text-center text-sm text-[#568996]">Als Naechstes legen wir Prioritaeten fest.</span>
          <button
            type="button"
            class="w-full rounded-[4px] border border-[#003745] bg-white px-4 py-3 font-medium text-[#003745] transition-colors hover:bg-[#F4F9FA]"
            @click="handleCalculateClick"
          >
            Betrag ermitteln
          </button>
        </div>
      </article>
    </div>
  </div>
</template>
