// src/app/components/ui/NumericInputStepper.vue
<script setup lang="ts">
const props = withDefaults(
  defineProps<{
    value: number
    label?: string
    unit?: string
    note?: string
    min?: number
    max?: number
    step?: number
  }>(),
  {
    label: '',
    unit: '',
    note: '',
    min: 0,
    max: 100,
    step: 1,
  },
)

const emit = defineEmits<{
  (event: 'update:value', value: number): void
}>()

const handleDecrement = () => {
  if (props.value <= props.min) {
    return
  }

  emit('update:value', Math.max(props.min, props.value - props.step))
}

const handleIncrement = () => {
  if (props.value >= props.max) {
    return
  }

  emit('update:value', Math.min(props.max, props.value + props.step))
}
</script>

<template>
  <div class="flex w-full flex-col">
    <span v-if="props.label" class="mb-[4px] block text-[12px] font-normal text-[#568996]">
      {{ props.label }}
    </span>

    <div class="flex h-[40px] items-center overflow-hidden rounded-[4px] border border-[#003745] bg-[#FFFFFF]">
      <button
        type="button"
        :disabled="props.value <= props.min"
        class="flex h-full w-[40px] items-center justify-center bg-transparent text-[#003745] focus:outline-none disabled:opacity-50"
        @click="handleDecrement"
      >
        -
      </button>

      <div class="flex flex-grow items-center justify-center gap-[6px]">
        <span class="text-[16px] font-semibold text-[#003745]">
          {{ props.value }}
        </span>
        <span v-if="props.unit" class="text-[14px] font-semibold text-[#003745]">
          {{ props.unit }}
        </span>
      </div>

      <button
        type="button"
        :disabled="props.value >= props.max"
        class="flex h-full w-[40px] items-center justify-center bg-transparent text-[#003745] focus:outline-none disabled:opacity-50"
        @click="handleIncrement"
      >
        +
      </button>
    </div>

    <span v-if="props.note" class="mt-[4px] block text-[12px] font-normal text-[#568996]">
      {{ props.note }}
    </span>
  </div>
</template>

// src/app/components/ui/NumericInputStepper.tsx
import * as React from "react"
import { Minus, Plus } from "lucide-react"
import { cn } from "./utils"

interface NumericInputStepperProps {
  value: number
  onChange: (value: number) => void
  label?: string
  unit?: string
  note?: string
  min?: number
  max?: number
  step?: number
  className?: string
}

export function NumericInputStepper({
  value,
  onChange,
  label,
  unit,
  note,
  min = 0,
  max = 100,
  step = 1,
  className,
}: NumericInputStepperProps) {
  
  const handleDecrement = () => {
    if (value > min) {
      onChange(Math.max(min, value - step))
    }
  }

  const handleIncrement = () => {
    if (value < max) {
      onChange(Math.min(max, value + step))
    }
  }

  return (
    <div className={cn("flex flex-col w-full", className)}>
      {label && (
        <span className="text-[12px] text-[#568996] mb-[4px] block font-normal">
          {label}
        </span>
      )}
      
      <div className="flex items-center bg-[#FFFFFF] border border-[#003745] rounded-[4px] h-[40px] overflow-hidden">
        <button
          type="button"
          onClick={handleDecrement}
          disabled={value <= min}
          className="w-[40px] h-full flex items-center justify-center bg-transparent text-[#003745] disabled:opacity-50 focus:outline-none"
        >
          <Minus size={16} />
        </button>
        
        <div className="flex-grow flex items-center justify-center gap-[6px]">
          <span className="text-[16px] font-semibold text-[#003745]">
            {value}
          </span>
          {unit && (
            <span className="text-[14px] font-semibold text-[#003745]">
              {unit}
            </span>
          )}
        </div>

        <button
          type="button"
          onClick={handleIncrement}
          disabled={value >= max}
          className="w-[40px] h-full flex items-center justify-center bg-transparent text-[#003745] disabled:opacity-50 focus:outline-none"
        >
          <Plus size={16} />
        </button>
      </div>

      {note && (
        <span className="text-[12px] text-[#568996] mt-[4px] block font-normal">
          {note}
        </span>
      )}
    </div>
  )
}
